### ISSUE TITLE
configuration issue 

### ISSUE THREAD

**Issue by rameezashraf** [Gottwik/enduro_website#14]
Hi, i am newbie. i am trying to config enduro.js demo at local but i face error during run this demo ( Unhandled rejection Error: Cannot find module 'marked'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\workspace\enduro\enduro_website-master\app\abstractors\doc.js:5:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at glob.then (D:\workspace\enduro\Enduro-master\libs\abstractor\abstractor.js:35:60)
    at <anonymous>)

**Comment by Gottwik** [comment]
Hey, could you try running `npm i` in the project folder?

marked is a dependency(adds markdown) and needs to be installed.
